seqr:
  cronJobs: []
  clickhouse:
    enabled: true
  redis:
    image:
      repository: bitnamilegacy/redis
  postgresql:
    primary:
      initContainers:
        - name: seqr-postgresql-init-chmod-data
          image: busybox
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/sh
            - -ec
            - |
              mkdir -p {{ .Values.postgresqlDataDir }}
              chown -R `id -u`:`id -G | cut -d " " -f2` {{ .Values.postgresqlDataDir }}
              echo `id -u`:`id -G | cut -d " " -f2`
          # In theory this block is template-able but is getting wrapped in single quotes.
          securityContext:
            runAsGroup: 1001
            runAsNonRoot: false
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: data
              mountPath: /var/seqr
pipeline-runner:
  pods:
    - name: api
      service:
        type: ClusterIP
        port: 6000
      healthCheckRoute: /status
      command: ["python3", "-m", "v03_pipeline.api"]
      initContainers: {}
      resources: {}
      sidecar:
        command: ["python3", "-m", "v03_pipeline.bin.pipeline_worker"]
        privileged: true
    - name: ui
      service:
        type: NodePort
        port: 8082
        nodePort: 30951
      healthCheckRoute: /
      command: ["luigid"]
      initContainers: |-
        - name: mkdir-luigi-state
          image: busybox:1.35
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/mkdir', '-p', {{ .Values.environment.LUIGI_STATE_DIR }}]
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- tpl . $ | nindent 4 }}
          {{- end }}
      resources: {}
      sidecar: {}
  hailWorkerResources: |-
    requests:
      memory: 1Mi
