apiVersion: v2
name: hail-search
description: A Helm chart for deploying the hail backend of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr
  - https://github.com/broadinstitute/seqr-helm
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 0.2.2-dev
appVersion: "8d474f75af06a9e3beed052c7d8068dbfb79b66b"
dependencies:
  - name: lib
    version: 0.1.0
    repository: "file://../lib"
    import-values:
      - child: exports.global
        parent: global
