apiVersion: v2
name: hail-search
description: A Helm chart for deploying the hail backend of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr
  - https://github.com/broadinstitute/seqr-helm
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 0.2.6-dev
appVersion: "6e1be20414826c2743561b5747030b0c295d86ea"
dependencies:
  - name: lib
    version: 0.1.0
    repository: "file://../lib"
    import-values:
      - child: exports.global
        parent: global
