# Default values for hail_search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always
  # -- The docker image tag to pull from the repository
  # tag: "gcloud-dev"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources: 
  {}

# default environment variables
environment:
  DATASETS_DIR: '/datasets'
  SOURCE_DATASETS_DIR: ''
  GRCH38_SNV_INDEL_VERSION: ''
  GRCH38_MITO_VERSION: ''
  GRCH38_SV_VERSION: ''
  GRCH38_GCNV_VERSION: ''
  GRCH37_SNV_INDEL_VERSION: ''
  GRCH37_MITO_VERSION: ''
  GRCH37_SV_VERSION: ''
  GRCH37_GCNV_VERSION: ''

initContainers: |-
  - name: sync-datasets
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    command: ['/sync_datasets]
    volumeMounts:
      - mountPath: /datasets
        name: datasets

# Prefer to be scheduled away from other hail-search pods and other seqr application pods
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- include "hail-search.selectorLabels"  . | nindent 12 }}
          topologyKey: "kubernetes.io/hostname"
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "name"
                operator: In
                values:
                - seqr
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
