replicaCount: 1

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}
deploymentAnnotations: {}

service:
  type: ClusterIP
  port: 5000

resources:
  {}

environment:
  HAIL_SEARCH_DATA_DIR: '/seqr/seqr-hail-search-data'
  REFERENCE_DATASETS_DIR: '/seqr/seqr-reference-data'

persistentVolume:
  storageCapacity: ''
  driver: ''
  volumeHandle: ''

volumes: |-
  - name: seqr-datasets
    persistentVolumeClaim:
      readOnly: true
      claimName: {{ .Chart.Name }}-pvc-{{ .Values.persistentVolume.volumeHandle | sha256sum | trunc 5 }}
volumeMounts: |-
  - name: seqr-datasets
    mountPath: /seqr
    readOnly: true

initContainers: {}

# Prefer to be scheduled away from other seqr platform pods
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/part-of"
                operator: In
                values:
                - "seqr-platform"
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
tolerations: []

global:
  hail-search:
    datasetVersions:
      GRCh37/SNV_INDEL: ''
      GRCh38/SNV_INDEL: ''
