# Default values for hail_search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always
  # -- The docker image tag to pull from the repository
  # tag: "gcloud-dev"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8000

resources: {}

nodeSelector: {}
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- include "hail-search.selectorLabels"  . | nindent 12 }}
          topologyKey: "kubernetes.io/hostname"