# Default values for hail_search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always
  # -- The docker image tag to pull from the repository
  # tag: "gcloud-dev"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources: 
  {}

# default environment variables
environment:
  DATASETS_DIR: "/datasets"

datasetsRoot: ''
snvIndelVersion: ''
mitoVersion: ''
initContainers: |-
  - name: init-snvIndel
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', '-m', 'rsync', '-r', '{{ .Values.datasetsRoot }}/SNV_INDEL/{{ .Values.snvIndelVersion }}', '/datasets/SNV_INDEL']
    volumeMounts:
      - mountPath: /datasets/SNV_INDEL
        name: datasets
  - name: init-mito
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', '-m', 'rsync', '-r', '{{ .Values.datasetsRoot }}/MITO/{{ .Values.mitoVersion }}', '/datasets/MITO']
    volumeMounts:
      - mountPath:  /datasets/MITO
        name: datasets

# Prefer to be scheduled away from other hail-search pods and other seqr application pods
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- include "hail-search.selectorLabels"  . | nindent 12 }}
          topologyKey: "kubernetes.io/hostname"
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "name"
                operator: In
                values:
                - seqr
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
