# Default values for hail-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always
  # -- The docker image tag to pull from the repository
  # tag: "gcloud-dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

service:
  type: ClusterIP
  port: 5000

resources:
  {}

# default environment variables
environment:
  DATASETS_DIR: '/datasets'
  SSD_DATASETS_DIR: '/ssd-datasets'

initContainers: |-
  {{- range $path, $version := $.Values.global.hail_search.datasetVersions -}}
  {{ if $version }}
  - name: mkdir-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
    image: busybox:1.35
    command: ['/bin/mkdir', '-p', '{{ $.Values.environment.DATASETS_DIR }}/{{ $path | replace "SV" "SV_WGS" | replace "GCNV" "SV_WES"}}/projects']
    volumeMounts:
      - mountPath: {{ $.Values.environment.DATASETS_DIR }}
        name: datasets
  - name: mkdir-ssd-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
    image: busybox:1.35
    command: ['/bin/mkdir', '-p', '{{ $.Values.environment.SSD_DATASETS_DIR }}/{{ $path | replace "SV" "SV_WGS" | replace "GCNV" "SV_WES"}}/families']
    volumeMounts:
      - mountPath: {{ $.Values.environment.SSD_DATASETS_DIR }}
        name: ssd-datasets
  - name: sync-annotations-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', '-m', 'rsync', '-r', '{{ $.Values.global.hail_search.sourceDatasetsDir }}/{{ $path }}/runs/{{ $version }}/annotations.ht', '{{ $.Values.environment.DATASETS_DIR }}/{{ $path | replace "SV" "SV_WGS" | replace "GCNV" "SV_WES"}}/annotations.ht']
    volumeMounts:
      - mountPath: {{ $.Values.environment.DATASETS_DIR }}
        name: datasets
  - name: sync-metadata-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', 'cp', '{{ $.Values.global.hail_search.sourceDatasetsDir }}/{{ $path }}/runs/{{ $version }}/metadata.json', '{{ $.Values.environment.DATASETS_DIR }}/{{ $path | replace "SV" "SV_WGS" | replace "GCNV" "SV_WES"}}/metadata.json']
    volumeMounts:
      - mountPath: {{ $.Values.environment.DATASETS_DIR }}
        name: datasets
  - name: sync-projects-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', '-m', 'rsync', '-r', '{{ $.Values.global.hail_search.sourceDatasetsDir }}/{{ $path }}/runs/{{ $version }}/projects', '{{ $.Values.environment.DATASETS_DIR }}/{{ $path | replace "SV" "SV_WGS" | replace "GCNV" "SV_WES"}}/projects']
    volumeMounts:
      - mountPath: {{ $.Values.environment.DATASETS_DIR }}
        name: datasets
  - name: sync-families-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', '-m', 'rsync', '-r', '{{ $.Values.global.hail_search.sourceDatasetsDir }}/{{ $path }}/runs/{{ $version }}/families', '{{ $.Values.environment.SSD_DATASETS_DIR }}/{{ $path | replace "SV" "SV_WGS" | replace "GCNV" "SV_WES"}}/families']
    volumeMounts:
      - mountPath: {{ $.Values.environment.SSD_DATASETS_DIR }}
        name: ssd-datasets
  {{ end -}}
  {{ end }}
  {{- range $path, $queries := $.Values.cachedReferenceDatasetQueries -}}
  {{- range $query := $queries -}}
  - name: sync-crdq-{{ $path | replace "/" "-" | replace "_" "-" | lower}}-{{ $query | replace "_" "-" | lower}}
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['gsutil', '-m', 'cp', '-r', '{{ $.Values.sourceCachedReferenceDatasetQueriesDir }}/{{ $path }}/cached_reference_dataset_queries/{{ $query }}.ht', '{{ $.Values.environment.DATASETS_DIR }}/{{ $path }}']
    volumeMounts:
      - mountPath: {{ $.Values.environment.DATASETS_DIR }}
        name: datasets
  {{ end -}}
  {{ end }}

# Prefer to be scheduled away from other hail-search pods and seqr application pods
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- include "hail-search.selectorLabels"  . | nindent 12 }}
          topologyKey: "kubernetes.io/hostname"
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "name"
                operator: In
                values:
                - seqr
          topologyKey: "kubernetes.io/hostname"

nodeSelector:
  {}

sourceCachedReferenceDatasetQueriesDir: 'gs://seqr-reference-data/v03'
cachedReferenceDatasetQueries:
  GRCh38/SNV_INDEL:
    - 'clinvar_path_variants'
    - 'high_af_variants'
  GRCh38/MITO:
    - 'clinvar_path_variants'

global:
  hail_search:
    sourceDatasetsDir: ''
    datasetVersions:
      GRCh37/SNV_INDEL: ''
      GRCh38/SNV_INDEL: ''
