# Default values for hail-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always
  # -- The docker image tag to pull from the repository
  # tag: "gcloud-dev"

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}
deploymentAnnotations: {}

service:
  type: ClusterIP
  port: 5000

resources:
  {}

# default environment variables
environment:
  HAIL_SEARCH_DATA_DIR: '/seqr/seqr-hail-search-data'
  IN_MEMORY_DIR: '/in-memory-datasets'

inMemoryVolumeEnabled: false
persistentVolume:
  enabled: false
  storageCapacity: ''
  driver: ''
  volumeHandle: ''

initContainers: {}

# Prefer to be scheduled away from other seqr platform pods
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/part-of"
                operator: In
                values:
                - "seqr-platform"
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
tolerations: []

global:
  hail-search:
    datasetVersions:
      GRCh37/SNV_INDEL: ''
      GRCh38/SNV_INDEL: ''
