# Default values for hail_search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: gcr.io/seqr-project/seqr-hail-search
  pullPolicy: Always
  # -- The docker image tag to pull from the repository
  # tag: "gcloud-dev"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources: 
  {}

# default environment variables
environment:
  DATASETS_DIR: '/datasets'
  SOURCE_DATASETS_DIR: ''
  GRCH37_SNV_INDEL_VERSION: ''
  GRCH38_SNV_INDEL_VERSION: ''
  GRCH38_MITO_VERSION: ''
  GRCH38_SV_VERSION: ''
  GRCH38_GCNV_VERSION: ''

initContainers: |-
  - name: sync-datasets
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['/bin/bash', '-c']
    args: 
      - echo "Syncing data";
        gsutil -m rsync -r {{ .Values.environment.SOURCE_DATASETS_DIR }}/GRCh37/SNV_INDEL/runs/{{ .Values.environment.GRCH37_SNV_INDEL_VERSION }} {{ .Values.environment.DATASETS_DIR }}/GRCh37/SNV_INDEL;
        gsutil -m rsync -r {{ .Values.environment.SOURCE_DATASETS_DIR }}/GRCh38/SNV_INDEL/runs/{{ .Values.environment.GRCH38_SNV_INDEL_VERSION }} {{ .Values.environment.DATASETS_DIR }}/GRCh38/SNV_INDEL;
        gsutil -m rsync -r {{ .Values.environment.SOURCE_DATASETS_DIR }}/GRCh38/MITO/runs/{{ .Values.environment.GRCH38_MITO_VERSION }} {{ .Values.environment.DATASETS_DIR }}/GRCh38/MITO;
        gsutil -m rsync -r {{ .Values.environment.SOURCE_DATASETS_DIR }}/GRCh38/SV/runs/{{ .Values.environment.GRCH38_SV_VERSION }} {{ .Values.environment.DATASETS_DIR }}/GRCh38/SV;
        gsutil -m rsync -r {{ .Values.environment.SOURCE_DATASETS_DIR }}/GRCh38/GCNV/runs/{{ .Values.environment.GRCH38_GCNV_VERSION }} {{ .Values.environment.DATASETS_DIR }}/GRCh38/GCNV;
    volumeMounts:
      - mountPath: {{ .Values.environment.DATASETS_DIR }}
        name: datasets

# Prefer to be scheduled away from other hail-search pods and other seqr application pods
affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- include "hail-search.selectorLabels"  . | nindent 12 }}
          topologyKey: "kubernetes.io/hostname"
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "name"
                operator: In
                values:
                - seqr
          topologyKey: "kubernetes.io/hostname"

nodeSelector: 
  {}
