apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane 
    extraMounts:
    - hostPath: /var/seqr
      containerPath: /var/seqr
      readOnly: false
    extraPortMappings:
    - containerPort: 30950 # the seqr app exposes a NodePort on this port
      hostPort: 80
    - containerPort: 30951 # the luigi scheduler exposes a NodePort on this port
      hostPort: 8082
