replicaCount: 1

image:
  repository: gcr.io/seqr-project/seqr-vlm
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}
deploymentAnnotations: {}

service:
  type: NodePort
  port: 7000
  nodePort: 30952

resources:
  {}

environment:
  VLM_DATA_DIR: '/var/seqr/seqr-hail-search-data'
  SEQR_BASE_URL: ''
  NODE_ID: ''

volumes: |-
  - name: seqr-datasets
    persistentVolumeClaim:
      readOnly: true
      claimName: {{ include "lib.pvc-name" . }}
volumeMounts: |-
  - name: seqr-datasets
    mountPath: /var/seqr
    readOnly: true

initContainers: {}

affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/part-of"
                operator: In
                values:
                - "seqr-platform"
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
tolerations: []

global:
  seqrPlatformDeploy: false
