replicaCount: 1

image:
  repository: gcr.io/seqr-project/seqr-vlm
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}
deploymentAnnotations: {}

service:
  type: NodePort
  port: 7000
  nodePort: 30952

resources:
  {}

environment:
  CLICKHOUSE_SERVICE_HOSTNAME: 'seqr-clickhouse'
  CLICKHOUSE_SERVICE_PORT: '8123'
  CLICKHOUSE_VLM_USERNAME: 'vlm_clickhouse_reader'
  SEQR_BASE_URL: ''
  NODE_ID: ''

requiredSecrets:
  vlmSecretName: vlm-secrets

initContainers: {}

affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/part-of"
                operator: In
                values:
                - "seqr-platform"
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
tolerations: []

networkPolicy:
  enabled: false
