apiVersion: v2
name: seqr-platform
description: A Helm chart for deploying all components of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr-helm
  - https://github.com/broadinstitute/seqr
  - https://github.com/broadinstitute/seqr-loading-pipelines
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 2.4.1
dependencies:
  - name: seqr
    version: 3.9.0
    repository: "https://broadinstitute.github.io/seqr-helm"
  - name: pipeline-runner
    version: 2.42.0
    repository: "https://broadinstitute.github.io/seqr-helm"
    condition: pipeline-runner.enabled
  - name: vlm
    version: 2.2.0
    repository: "https://broadinstitute.github.io/seqr-helm"
    condition: vlm.enabled
  - name: lib
    version: 1.1.0
    repository: "https://broadinstitute.github.io/seqr-helm"
    import-values:
      - child: exports.global
        parent: global
