apiVersion: v2
name: seqr-platform
description: A Helm chart for deploying all components of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr-helm
  - https://github.com/broadinstitute/seqr
  - https://github.com/broadinstitute/seqr-loading-pipelines
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 0.1.0-dev
dependencies:
  - name: seqr
    version: 1.1.7-dev
    repository: "file://../seqr"
  - name: pipeline-runner
    version: 0.1.2-dev
    repository: "file://../pipeline-runner"
    condition: pipeline-runner.enabled
  - name: hail-search
    version: 0.2.8-dev
    repository: "file://../hail-search"
  - name: lib
    version: 0.1.3
    repository: "file://../lib"
    import-values:
      - child: exports.global
        parent: global
