apiVersion: v2
name: seqr-platform
description: A Helm chart for deploying all components of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr-helm
  - https://github.com/broadinstitute/seqr
  - https://github.com/broadinstitute/seqr-loading-pipelines
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 0.3.3
dependencies:
  - name: seqr
    version: 1.4.0
    repository: "https://broadinstitute.github.io/seqr-helm"
  - name: pipeline-runner
    version: 0.2.2
    repository: "https://broadinstitute.github.io/seqr-helm"
    condition: pipeline-runner.enabled
  - name: hail-search
    version: 0.5.0
    repository: "https://broadinstitute.github.io/seqr-helm"
  - name: vlm
    version: 0.0.1
    repository: "https://broadinstitute.github.io/seqr-helm"
    condition: vlm.enabled
  - name: lib
    version: 0.1.4
    repository: "https://broadinstitute.github.io/seqr-helm"
    import-values:
      - child: exports.global
        parent: global
