apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "vlm.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "vlm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vlm.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/environment.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-pod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          env:
            - name: VLM_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.requiredSecrets.vlmSecretName }}
                  key: client_id
            - name: VLM_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.requiredSecrets.vlmSecretName }}
                  key: client_secret
            - name: CLICKHOUSE_VLM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.requiredSecrets.vlmSecretName }}
                  key: seqr_clickhouse_vlm_password
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 10
            failureThreshold: 5
            httpGet:
              path: /vlm/status
              port: http
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 10
            failureThreshold: 5
            httpGet:
              path: /vlm/status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      {{- with .Values.initContainers}}
      initContainers:
        {{- tpl . $ | trim | nindent 8}}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
