apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-deny-egress
  labels:
    {{- include "vlm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  policyTypes:
    - Egress
  {{- with .Values.egress }}
  egress:
    {{- tpl . $ | trim | nindent 4 }}
  {{- end }}
