apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-cluster-deny-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: seqr