{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-ingress-to-clickhouse
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}