apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-cluster-deny-ingress
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: seqr