{{- range $p := .Values.pods }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $p.name }}
  labels:
    {{- include "pipeline-runner.labels" $ | nindent 4 }}
  {{- with $.Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "pipeline-runner.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pipeline-runner.labels" $ | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/environment.yaml") $ | sha256sum }}
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
      - name: seqr
        persistentVolumeClaim:
          claimName: {{ include "seqr-platform.pvc-name" $ }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ $.Chart.Name }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $p.name }}-pod
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          command: ["/bin/bash", "-c"]
          args: {{ $p.command }}
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}
          ports:
            - name: http
              containerPort: {{ $p.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 5
            httpGet:
              path: {{ $p.healthCheckRoute }}
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 5
            httpGet:
              path: {{ $p.healthCheckRoute }}
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /seqr
              name: seqr
        {{- with $p.sidecar }}
        - name: {{ $.Chart.Name }}-{{ $p.name }}-pod-sidecar
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          command: ["/bin/bash", "-c"]
          args: {{ .command }}
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /seqr
              name: seqr
        {{- end }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      {{- with $p.initContainers}}
      initContainers:
        {{- tpl . $ | trim | nindent 8}}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
