apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "pipeline-runner.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  { { - with .Values.global.seqr.environment } }
    { { - toYaml . | nindent 2 } }
  { { - end } }
