apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "pipeline-runner.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  SEQR_APP_HAIL_SEARCH_DATA_DIR: {{ .Values.global.HAIL_SEARCH_DATA_DIR | quote }}
