apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "pipeline-runner.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if ne .Values.environment.HAIL_SEARCH_DATA_DIR .Values.global.SEQR_APP_HAIL_SEARCH_DATA_DIR }}
  SEQR_APP_HAIL_SEARCH_DATA_DIR: {{ .Values.global.SEQR_APP_HAIL_SEARCH_DATA_DIR | quote }}
  {{- end }}
