{{- range $s := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $s.name }}
  labels:
    {{- include "pipeline-runner.labels" $ | nindent 4 }}
spec:
  type: {{ $s.type }}
  ports:
    - port: {{ $s.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ $.Chart.Name }}-{{ $s.name }}
    {{- include "pipeline-runner.selectorLabels" $ | nindent 4 }}
{{ end }}
