apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hail-search.fullname" . }}
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hail-search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hail-search.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: datasets
        emptyDir:
          # Default sizeLimit is 1/2 the total RAM of the Node.
          medium: "Memory"
      containers:
        - name: {{ include "hail-search.fullname" . }}-pod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /datasets
              name: datasets
      {{- with .Values.initContainers }}
      initContainers:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
