apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- range $key, $value := . }}
      {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
