{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "hail-search.fullname" . }}-pv
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  capacity:
    storage: 2000G
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: {{ include "hail-search.fullname" . }}-pvc
  csi:
    driver: {{ .Values.persistentVolume.driver }}
    volumeHandle: {{ .Values.persistentVolume.volumeHandle }}
    fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hail-search.fullname" . }}-pvc
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ include "hail-search.fullname" . }}-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2000G
{{- end }}