apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{- include "hail-search.pv-name" . }}
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.persistentVolume.storageCapacity }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: {{- include "hail-search.pvc-name" . }}
    # namespace appears to default to '' here.
    # https://stackoverflow.com/questions/68289505/is-namespace-mandatory-while-defining-claimref-under-k8s-persistentvolume-manife
    # https://github.com/kubernetes/kubernetes/issues/48609 (loosely related)
    namespace: default
  {{- with .Values.persistentVolume.csi }}
  csi:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.persistentVolume.csi }}
  local:
    path: {{ .Values.global.environment.HAIL_SEARCH_DATA }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{- include "hail-search.pvc-name" . }}
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{- include "hail-search.pv-name" . }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storageCapacity }}