{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "hail-search.fullname" . }}-pv-{{ print .Values.persistentVolume.volumeHandle | sha256sum | trunc 5}}
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.persistentVolume.storageCapacity }}
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: {{ include "hail-search.fullname" . }}-pvc-{{ print .Values.persistentVolume.volumeHandle | sha256sum | trunc 5}}
    # namespace appears to default to '' here.
    # https://stackoverflow.com/questions/68289505/is-namespace-mandatory-while-defining-claimref-under-k8s-persistentvolume-manife
    # https://github.com/kubernetes/kubernetes/issues/48609 (loosely related)
    namespace: default
  csi:
    driver: {{ .Values.persistentVolume.driver }}
    volumeHandle: {{ .Values.persistentVolume.volumeHandle }}
    fsType: 'ext4'
    readOnly: True
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hail-search.fullname" . }}-pvc-{{ print .Values.persistentVolume.volumeHandle | sha256sum | trunc 5}}
  labels:
    {{- include "hail-search.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ include "hail-search.fullname" . }}-pv-{{ print .Values.persistentVolume.volumeHandle | sha256sum | trunc 5}}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storageCapacity }}
{{- end }}
