{{- if $.Values.persistentVolume.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: describe-pv
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - ['pvc']
  verbs:
  - ['describe']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: describe-pv-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: describe-pv
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hail-search.fullname" $ }}-prune-pvc
  labels:
    {{- include "hail-search.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      annotations:
        {{- with $.Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "hail-search.selectorLabels" $ | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "hail-search.fullname" $ }}-prune-pvc
          image: bitnami/kubectl
          command: ["/bin/bash", "-c"]
          args:
            - kubectl describe pvc seqr-hail-search-pvc | grep -E "^Name:.*$|^Used By:.*$" | grep -B1 '<none>' | grep -E "^Name:.*$" | awk '{print $2}' | xargs -I{} kubectl delete pvc {}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
