apiVersion: v2
name: pipeline-runner
description: A Helm chart for deploying the loading pipeline of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr-helm
  - https://github.com/broadinstitute/seqr-loading-pipelines
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 2.189.0
appVersion: "58ab39c60d29ea628236ab8a6d16e5c5509cb4de"
dependencies:
  - name: lib
    version: 1.1.0
    repository: "file://../lib"
    import-values:
      - child: exports.global
        parent: global
