apiVersion: v2
name: pipeline-runner
description: A Helm chart for deploying the loading pipeline of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr-helm
  - https://github.com/broadinstitute/seqr-loading-pipelines
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 2.191.0
appVersion: "879a17ca0d90cdbc4104a78f6a60d1d340898f87"
dependencies:
  - name: lib
    version: 1.1.0
    repository: "file://../lib"
    import-values:
      - child: exports.global
        parent: global
