apiVersion: v2
name: pipeline-runner
description: A Helm chart for deploying the loading pipeline of Seqr, an open source software platform for rare disease genomics
sources:
  - https://github.com/broadinstitute/seqr-helm
  - https://github.com/broadinstitute/seqr-loading-pipelines
maintainers:
  - name: seqr
    email: seqr@broadinstitute.org
type: application
version: 2.178.0
appVersion: "1166b3ba0b6a83fefe9b71a8a91cf0312d3b952d"
dependencies:
  - name: lib
    version: 1.1.0
    repository: "file://../lib"
    import-values:
      - child: exports.global
        parent: global
