image:
  repository: gcr.io/seqr-project/seqr-pipeline-runner
  pullPolicy: Always
imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}
deploymentAnnotations: {}

requiredSecrets:
  postgresSecretName: postgres-secrets

additionalSecrets: {}
volumes: |-
  - name: seqr-datasets
    persistentVolumeClaim:
      readOnly: false
      claimName: {{ include "lib.pvc-name" . }}
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  - name: luigi-config
    configMap:
      name: luigi-config
      items:
        - key: luigi.cfg
          path: luigi.cfg
volumeMounts: |-
  - name: seqr-datasets
    mountPath: /var/seqr
    readOnly: false
  - name: docker-socket
    mountPath: /var/run/docker.sock
    readOnly: false
  - name: luigi-config
    mountPath: /etc/luigi/luigi.cfg
    subPath: luigi.cfg

pods:
  - name: api
    service:
      type: ClusterIP
      port: 6000
    healthCheckRoute: /status
    command: ["python3", "-m", "v03_pipeline.api"]
    initContainers: |-
      {{- range $r := list "GRCh37" "GRCh38" }}
      {{- range $s := list "rsync_reference_data" "download_vep_reference_data"}}
      - name: {{ $s | replace "_" "-" }}-{{ $r | lower}}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["/v03_pipeline/bin/{{ $s }}.bash", "{{ $r }}"]
        envFrom:
          - configMapRef:
              name: {{ $.Chart.Name }}
          - configMapRef:
              name: seqr-platform
              optional: true
        resources:
          requests:
            memory: "12Gi"
        {{- with $.Values.volumeMounts }}
        volumeMounts:
          {{- tpl . $ | nindent 4 }}
        {{- end }}
      {{- end }}
      {{- end }}
    resources: {}
    sidecar:
      command: ["python3", "-m", "v03_pipeline.bin.pipeline_worker"]
      privileged: true
      resources:
        requests:
          # Default memory request because the worker runs HAIL.
          memory: "12Gi"
  - name: ui
    service:
      type: NodePort
      port: 8082
      nodePort: 30951
    healthCheckRoute: /
    command: ["luigid"]
    initContainers: |-
      - name: mkdir-luigi-state
        image: busybox:1.35
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['/bin/mkdir', '-p', {{ .Values.environment.LUIGI_STATE_DIR }}]
        {{- with $.Values.volumeMounts }}
        volumeMounts:
          {{- tpl . $ | nindent 4 }}
        {{- end }}
    resources: {}
    sidecar: {}

resources: {}
environment:
  HAIL_SEARCH_DATA_DIR: "/var/seqr/seqr-hail-search-data"
  REFERENCE_DATASETS_DIR: "/var/seqr/seqr-reference-data"
  LUIGI_STATE_DIR: "/var/seqr/luigi-state"
  SHOULD_TRIGGER_HAIL_BACKEND_RELOAD: "1"

  POSTGRES_SERVICE_HOSTNAME: "seqr-postgresql"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_SERVICE_PORT: "5432"

affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1.0
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/part-of"
                operator: In
                values:
                - "seqr-platform"
          topologyKey: "kubernetes.io/hostname"
nodeSelector: {}
tolerations: []

global:
  seqrPlatformDeploy: false
