{{- range $path, $version := $.Values.global.hail_search.datasetVersions -}}
{{ if and $.Values.check_for_new_samples_job_enabled $version }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Chart.Name }}-check-new-samples-job-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
  labels:
    {{- include "seqr.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ $.Chart.Name }}-check-new-samples-job-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
      labels:
        {{- include "seqr.labels" $ | nindent 8 }}
      annotations:
        {{- with $.Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ $.Chart.Name }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-check-new-samples-job-{{ $path | replace "/" "-" | replace "_" "-" | lower}}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "seqr.environment" $ | nindent 10}}
          command: ["/bin/bash", "-c"]
          args:
            - echo starting check new samples job;
            {{- if $.Values.jobBeforeHook}}
              {{ $.Values.jobBeforeHook }};
            {{- end }}
            {{- if $.Values.jobAfterHook}}
              trap "{{ $.Values.jobAfterHook }}" EXIT;
            {{- end }}
              python manage.py check_for_new_samples_from_pipeline {{ $path }} {{ $version }};
      {{- with $.Values.deployment_sidecars }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
{{ end }}
