{{- if .Values.clickhouse.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: seqr-clickhouse-configd-config
  labels:
    {{- include "seqr.labels" $ | nindent 4 }}
data:
  00_seqr_config.xml: |
    <clickhouse>
      <path>{{ $.Values.environment.CLICKHOUSE_DATA_DIR }}/</path>
      <user_files_path>{{ $.Values.environment.CLICKHOUSE_DATA_DIR }}/user_files/</user_files_path>
      <tmp_path>{{ $.Values.environment.CLICKHOUSE_DATA_DIR }}/tmp/</tmp_path>
      <user_directories>
        <local_directory>
          <path>{{ $.Values.environment.CLICKHOUSE_DATA_DIR }}/access/</path>
        </local_directory>
      </user_directories>
      <format_schema_path>{{ $.Values.environment.CLICKHOUSE_DATA_DIR }}/format_schemas/</format_schema_path>
    </clickhouse>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seqr-clickhouse-usersd-config
  labels:
    {{- include "seqr.labels" $ | nindent 4 }}
data:
  00_seqr_config.xml: |
    <clickhouse>
      <profiles>
        <default>
          <flatten_nested>0</flatten_nested>
          <join_use_nulls>1</join_use_nulls>

          <!-- Added to enable clean staging of large projects that may exceed the default (50GB) -->
          <max_partition_size_to_drop>250000000000</max_partition_size_to_drop>
          <max_table_size_to_drop>250000000000</max_table_size_to_drop>

          <!-- Reduces the memory bloat of the dictionary group by. -->
          <max_bytes_ratio_before_external_group_by>0.1</max_bytes_ratio_before_external_group_by>
          <max_bytes_ratio_before_external_sort>0.1</max_bytes_ratio_before_external_sort>
        </default>
      </profiles>
    </clickhouse>
{{- end }}