---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seqr.fullname" . }}
  labels:
    {{- include "seqr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "seqr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "seqr.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/environment.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "seqr.labels" . | nindent 8 }}
    spec:
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "seqr.fullname" . }}
      {{- end }}
      containers:
      - name: {{ include "seqr.fullname" . }}
        ports:
        - containerPort: 8000
          protocol: TCP
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- include "seqr.environment" $ | nindent 8 }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
          failureThreshold: 6
          periodSeconds: 10
      {{- with .Values.deployment_sidecars }}
        {{- tpl . $ | nindent 6 }}
      {{- end }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}