---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ $.Chart.Name }}
    {{- include "seqr.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: {{ $.Chart.Name }}
      {{- include "seqr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ $.Chart.Name }}
        {{- include "seqr.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/environment.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.volumes }}
      volumes:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Chart.Name }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        ports:
        - containerPort: 8000
          protocol: TCP
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- tpl . $ | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- include "seqr.environment" $ | nindent 8 }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
          failureThreshold: 60
          periodSeconds: 15
      {{- with .Values.deploymentSidecars }}
        {{- tpl . $ | nindent 6 }}
      {{- end }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      {{- with .Values.initContainers }}
      initContainers:
        {{- tpl . $ | trim | nindent 8}}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
