apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seqr.fullname" . }}
  labels:
    {{- include "seqr.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
