apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "seqr.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.globals.seqr.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
