kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "seqr.fullname" . }}-environment
  labels:
    {{- include "seqr.labels" . | nindent 4 }}
data:
  {{- with .Values.environment }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
