{{- if not .Values.global.seqrPlatformDeploy }}
{{- include "lib.persistentvolume" . }}
{{- end }}
{{- if .Values.clickhouse.enabled}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seqr-clickhouse-pv
  labels:
    {{- include "seqr.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.clickhouse.persistence.size }}
  accessModes:
    {{- range .Values.clickhouse.persistence.accessModes }}
      - {{ . | quote }}
    {{- end }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name:  seqr-clickhouse-pvc
    # namespace appears to default to '' here.
    # https://stackoverflow.com/questions/68289505/is-namespace-mandatory-while-defining-claimref-under-k8s-persistentvolume-manife
    # https://github.com/kubernetes/kubernetes/issues/48609 (loosely related)
    namespace: {{ .Release.Namespace }}
  csi:
    driver: pd.csi.storage.gke.io
    fsType: 'ext4'
    readOnly: True
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seqr-clickhouse-pv
  labels:
    {{- include "seqr.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: seqr-clickhouse-pv
  accessModes:
    {{- range .Values.clickhouse.persistence.accessModes }}
      - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }}
{{- end }}
