name: unit tests

# Run the test suite on pushes (incl. merges) to main
# Run the test suite when a PR is opened, pushed to, or reopened
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
      - name: Add bitnami
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Chart Lint
        run: ct lint --all
      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
      - name: Run Chart Templating Unit Tests
        run: python3 -m unittest unit_test/**/*.py
      #- name: Test hail search install
      #  run: ct install --charts charts/hail-search
