replicaCount: 4
podAnnotations:
  linkerd.io/inject: enabled
deploymentAnnotations:
  a/deployment: 'hello world'

nodeSelector:
  cloud.google.com/gke-nodepool: "test-pool"

tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

clusterHostname: &clusterHostname "test-seqr.myinstitute.org"

resources:
  requests:
    memory: "0.5Gi"
    cpu: "0.05"
  limits:
    memory: "35Gi"
    cpu: "8"

environment:
  DEPLOYMENT_TYPE: "test"
  BASE_URL: "https://test-seqr.myinstitute.org/"

redis:
  enabled: yes
  architecture: standalone
  auth:
    enabled: no
  master:
    podAnnotations:
      linkerd.io/inject: enabled
      config.linkerd.io/opaque-ports: "6379"
    resources:
      limits:
        memory: "10Gi"
        cpu: "1"
      requests:
        memory: "0.25Gi"
        cpu: "0.01"

deploymentSidecars: |-
  - name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:1.0.0
    command:
      - "/cloud-sql-proxy"
    startupProbe:
      httpGet:
        path: /startup
        port: 9090
      periodSeconds: 1
      timeoutSeconds: 5
      failureThreshold: 20
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9090
      initialDelaySeconds: 0
      periodSeconds: 60
      timeoutSeconds: 30
      failureThreshold: 5


jobAfterHook: "curl -s -m 60 -o /dev/null -X POST localhost:9091/quitquitquit; curl -s -m 60 -o /dev/null -X POST localhost:4191/shutdown; echo 'Pinged shutdown routes'"
jobBeforeHook: "/wait_for_routes localhost:9091/readiness localhost:4191/ready"
cronJobs:
  - name: test-cron-1
    schedule: "1 0 * * 0"
    command: "python /seqr/manage.py test_1 key=$KEY"
  - name: test-cron-2
    schedule: "2 0 * * 0"
    command: "python /seqr/manage.py test_2"

volumes: |-
  - name: matchbox-secrets-volume
    secret:
      secretName: matchbox-secrets
volumeMounts: |-
  - name: matchbox-secrets-volume
    mountPath: /mme

ingress:
  enabled: true
  nameOverride: ingress-nginx
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
  hosts:
    - host: *clusterHostname
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: nginx-secrets-cert-manager
      hosts:
        - *clusterHostname

additionalSecrets:
  - name: OMIM_KEY
    valueFrom:
      secretKeyRef:
        name: seqr-secrets
        key: omim_key

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: test-service-account@developer.gserviceaccount.com

clickhouse:
  enabled: true
  additionalSidecars: |-
    - name: rsync-rocksdbs
      image: google/cloud-sdk:slim
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        - |
          while true; do
            sleep 7d
          done
      env:
        - name: CLICKHOUSE_DATA_DIR
          value: |-
            {{ .Values.global.seqr.environment.CLICKHOUSE_DATA_DIR }}
      volumeMounts:
        - name: data
          mountPath: |-
            {{ .Values.persistence.mountPath }}
  additionalUsersdFiles: |-
    02_deployment_seqr_users_config.xml: 
      <clickhouse>
        <profiles>
          <default>
            <an_internal_setting>0</an_internal_setting>
          </default>
        </profiles>
      </clickhouse>
